---
- name: Pull Docker Image from Docker Hub
  hosts: all
  become: true
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "prashantjain31/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: sudo docker run -it -d --name calculator prashantjain31/calculator
